
server:
  port: 9002
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'

#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      table-prefix: bz_
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #this can allow u review the sql in log

#spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///target?serverTimezone=UTC
    username: root
    password: root

#dubbo
dubbo:
  application:
    name: target_admin_service
  registry:
    address: zookeeper://192.168.66.100 #VM ip addr
    port: 2181
    timeout: 10000 #the registry won stop without a timeout restrict
  protocol:
    name: dubbo
    port: -1 #-1 auto distribute
  scan:
    base-packages: com.target.target_admin_service.service

